[package]
name = "aoc-2025"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["target/aoc/aoc-autobuild"]

[dependencies]
aoc-runner = "*"
aoc-runner-derive = "*"
fixedbitset = "0.5.7"
petgraph = "0.8.3"
